services:
  - type: web
    name: colab-task-manager
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: colab-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://colab-task-manager.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://colab-task-manager.onrender.com

databases:
  - name: colab-db
    type: postgres
    region: ohio
    plan: free
